export const headerConfig = [
  { title: "#", field: "id" },
  { title: "TXN_ID", field: "transactionId" },
  { title: "Карта", field: "pan" },
  { title: "Срок действия", field: "expdate" },
  { title: "Тип транзакции", field: "transactionType" },
  { title: "RRN", field: "rrn" },
  { title: "STAN", field: "stan" },
  { title: "Сумма траназкции", field: "amount" },
  { title: "Валюта транзакции", field: "currencyCode" },
  { title: "Сист. Дата и время", field: "opDate" },
  { title: "Тран. Дата и время", field: "txnDateTime" },
  { title: "Лок. дата и время", field: "localDateTime" },
  { title: "MTI", field: "mti" },
  { title: "Код института эмитента", field: "issInst" },
  { title: "Мерчант", field: "merchantId" },
  { title: "MCC", field: "mcc" },
  { title: "Страна", field: "countryCode" },
  { title: "ID терминала", field: "terminalId" },
  { title: "Тип терминала", field: "terminalType" },
  { title: "POS_DATA_CODE", field: "posDataCode" },
  { title: "Метод чтения карты", field: "panEntryMode" },
  { title: "Код авторизации", field: "authorizationCode" },
  { title: "Внутренний код ответа", field: "internalResponseCode" },
  { title: "Код ответа хоста", field: "hostResponseCode" },
  { title: "Код ответа Фрод-мониторинга", field: "fraudVerdict" }
];
